# ========================================================================================================================================
# Project:     Juypter-Tensorflow-Service
# Pass-ID:     X9448776
# Author:      Atakan Çetinkaya
# Created:     30.05.2023
# Description: This .yaml (jupyter-tensorflow.yaml) File is installing all necessary configs for the JP-Notebook combined with Tensorflow
# File Name:   jupyter-tensorflow.yaml
# Version:     v0.8
# ========================================================================================================================================
apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-pv-claim
  namespace: demo
spec:
  storageClassName: block-nvme-lga1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tensorflow-jupyter
  namespace: demo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tensorflow-jupyter
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tensorflow-jupyter
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: jupyter-pv-claim
      containers:
        - name: tf
          image: tensorflow/tensorflow:2.12.0-gpu-jupyter
          ports:
            - name: notebook
              containerPort: 8888
              protocol: TCP
          resources:
            requests:
              cpu: 500m # The CPU unit is milli-cores. 500m is 0.5 cores
              memory: 256Mi
            limits:
              cpu: 2000m
              memory: 2048Mi
          volumeMounts:
            - name: storage
              mountPath: /tf/notebooks
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: public
    metallb.universe.tf/allow-shared-ip: example-1
  name: tensorflow-jupyter
  namespace: demo
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: notebook
      port: 8888
      protocol: TCP
      targetPort: notebook
  selector:
    app.kubernetes.io/name: tensorflow-jupyter
